### ISSUE TITLE
SEO Image

### ISSUE THREAD

**Issue by vre2h** [vre2h/bootcamp-html-project#5]
We need a pic `1200x630`

**Comment by hov001** [comment]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUVFBcUFRUXFxcaFxcXGhsbGxoXGxsaGhcYGBcXFxcbICwkGyApIBcbJTYlKS4wMzMzGiI5PjkxPSwyMzABCwsLEA4QHRISHjIpIiowMjIyMDIyMjMyMjIyMzIyMjIyMjIyMjIyMjI0MjIyMjIyMjIyMjIyMjIyMjIyMjIyMv/AABEIAKMBNgMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAADBAACBQEGB//EAEIQAAECAwUFBgUDAwEHBQEAAAEAAgMRIQQSMUFRYXGBkaEFEyIysdFCUmLB8AZyghSS4SMVFkNTosLxNGNzstIk/8QAGgEAAgMBAQAAAAAAAAAAAAAAAQQAAgMFBv/EADERAAIBAgUCBAUEAgMAAAAAAAABAgMRBBIhMUETURRhgaEFcZGxwSIy4fBC0SNSYv/aAAwDAQACEQMRAD8A+MqLqitYBxRdXELMJFFF1SxDiiiiliHQuKIoExt9d21GwAQRmNmJbab9OKEiw3yNag0I2IpEBEKJu0QqTxoCTqDg77HbxSiDViJl2uwPA7lHMkZfksj1RIDZhzcyJjeMuU+is2oBPw0O1pP2J6hHLoS4qiOz3g/nNSI2TiERzKA6tnyMvQKW0Jce/TH/AKuD/wDIFnxWG8R9RA5kLQ/Tbf8A+qFseFWHAPfsBwLmv4HxlU5BfUXtDPFEPyucOt0fmxAeJAD8ma+klovhzgXs3xzX6Ze6Xs7Lxv5B0/V32CPASOhTeGD4Q1vH4j/cSgthXnSGFTPZr6c0/YYB7qLHdkbjdr3znyaSeITFisvdw+8cMaiecvK2WkzM7AVL8BSM+JDJIhjLxO/cddwkOaloAAByFG7Tm4/mgyK0oNlIbM+Z5JcToKnhmeAVLNZg9190xDbRo1Aw4k9TsVHLU3jTbSS3YnDgXWzdQuFdQ3QbSlb1fCKmglluT/aMQkyaKuMqV/iOias1mEATIDopFBiGDMnarZtAdO8rLZCESCIbZHzHH2StwmbjQD8kFrw7AX/6j5yPlGb/AKtgnny1Vf6IxHSoGjE4ABWjpuWdNy0itDLgQHPMmimuQG0p6JchC6PE7M++g2c0eO4NbdhiQ1zO0aDake7DKvq7ENyG12p2c9FLNgcVDTkGWk+J5kMtT+0adEF5nQCQGX5iUyITnum6dcBmfYK8QXPKBPXIbtTtWkadzJiphXfNjk3PedENxJ9lctzM68yrCEZVoEXHhFUmwC6BqiGWXNEhwTiabSjGmS3YGAdy6mAWjCZUWuQlhFSSvJcks8hW5WSitJSSmREuVLVAdVcBWLQdiDp8olzjodJio199EJGY8tP5I7xmjGEHCbaH5f8A8n7KZLkbtuJyXWqxbJQBBwsS5HBFgwr1BicNDs3qzGTEuRyOxWMKkxMEeYabRs9EUgZuA1jE/AfNUsngTmw7HestSlI8KRmPKcNmoO0e2q02Qe9bebSIJXhhPRw4y4y1pe0Q77C80qBEEvK/BsSWhwO2eoVXZ/Mop6mPA8wrKqbfDLSDvY4fmRxG46KkeyuaA4iRnL2O6hTV+UicHAe0+ElIklLlAY8K69hyMsdji2vJN2WwOddbL4ojDxAb6vTnaFhLoTyPNDiB/wDCIAZ8Dd5latis4dChxR5hGhg8jInabwnrJZuasyuZ6GV+hrNetsNpyeOl6foqRrKWOhEiohdTeC9R+k+z7naYOXex2y0ud5T0PEIHaVgL4oY2krzePePawdEn1k6jXqMuH6VL0MeJYrlmYZUax7+LwQ2n7klAsJbZ2uM5xHkDdIEnq3qvbds9k3oTIbMHkDdDbEL5z5ckHs6zNiWgvDf9Kzhxa3IxJhjAeInwKvKurGsKLvr2M9/Y8+5sdGsgsMWO7IRH+J423RJv8ShPg946/K6wDwDG60UDiNQObnL1dosBYzuif9SK8GK7MAAOLeAIJ2vWPaXipaJzN1jcjLD+Inx4zWLrbj1LCuVl6mHaoU/BKpkCNG4tZy8R3jaqusjojhCh4Nlfd8LTk3bL1mtaz2MvmGHxfE86kzc7d7DVVtdoZCZ3cKp+bNzs3n7KrrapL++Z0IYOyd/X8Iy4sJsI+Gr2iQJ+CeMvrOZyw3XsVgmDEiCYOAOL9+jddZS3NWCwDGJlUg6nIpu0xAfE7yjysyMtdQOXoto1L6A8HlV2t+DMisLzeJk3M4Uwk0aUlTdhgraXikMCQ+UertTsTNojPdvOGwbBlv5IDbPIY7z9ppiCvq9jKdJ7RWolGnljrkOOZ/Al4VjJrzcfsFrMgg0An+dFaNCEpEj7f54JiLRg8G1tqzJfFaybWCZOJOJQ3WZ1HRDdBqBKZO5v3NFoSlVgA+t2X7R+Hcgd0CZ1c44udnwW0Xm2MpYW24lIfC3mZneT9lUQC7GvoFpssRNSJ76ALkUNaJF09goFqqfczeHdrvYziA3CpVXQnGrjIcky6KfhaBtKB3czUlx6K+UzlBLRf6RQFuQJ6KJkMO7ooq5TPJ5id0KvdcUQPGYRGlpVcojmaFu7XO74J5sKeBHH3VnQdRLqOYUyFeoZxYQutT7rMQJypqKhD7oHYeSFg9RMG1rXUND+YIrYIGP9w/7gq/07hhUI8G0DBwn0KjRVyfGpItkJEyJg4OFev2KVEGVHCmq2rPAdV0Eh4+JhFZbWZ7xhsTECBDjCTRdfmzP+BPmH0mR2lVaM+s4/L7GHAs7h5ZO1ZmRqBnwqm+7BaHtqMCMxsd9jgcKYJx/Zbm4V2YGf0zz+k134q8BtfEbrsL8vC7VsUZHbzniMp/p1RHVUhKzsuvAGB8pyE8WnVuX4VsiAL03CQc0tM/iFJtJ+YUkc/DhJcb2deBaGkOFbmJH1Qz8Q2aZlM2Rl+Hcdi00OmA5VA2TG5ZzaautzPqPMY0Wx3XGDEqAJtdqw4OGshlp+0Ib+z6CG6hB8JyJMpSOjvCZ5TOoXr7V2UYkO7/xWTfCfk+XmZtB9cqoPZ9kZHh93g+Rc0GlxzTVl7Q13cUm8SrX5Q2oS0fD+4Dsuzd5DM/M2FceCMWgkCfMDlwb7Fsty9ZzO865FZtcw36aza0jeSMlt2KzmHdikSI8MQS+YAFx33a7d652vYiyLDc2tyRZ+00A5NH95SHi1KVu+vqhrw7UbhoHZ3ddohwHhc+LEB/fCa77lBsXZofHe+RmzvHDSjmXafueV6a0NBiNfoxsthuOY4dOi7ZGthse4yq5v/U8U5iaQWI/5X8mjoxo3przaZl/qf/SYyGzEQ7plslQ8Up2DYhAhXnCZPjM83fCDrKnMo1rPeRZuqC9zz+0Hwt2Tn0VrdaLokanT8/OSMq99F3udClh9k+xndrRwA1gP+o8Eudow1cePi4LCbCvumKMFG7fyvNO203nmecrx4DwN2BJxbQACJyypkNB+equ6jaSR18LhlBORe0xg1l1tAeu0nRZUMBz/AA8zkM3LkWPfOzTXemBchipm4/DSm15+w5remrLUZdNPY6+JPwt8gNXanQan8ol7ZaGg4TIoBjLSYzOzAdBSPbJ4EDbkNjR90kIgyB+536BMxnZaGM6avq9f7sGDs3T268SrQxeq43WbMxs90uDMzJw5D3K66PMya2Z1NTwGA6piEpPVmbUIr8B41qAEmCTUqJvNBePJo3uKq9oFXGZ0nPmRRUfaCaZDADDl901C27+grUnwtApa3M3zs8LR/LE8FXvw2gEzoAlXPGZ4CvVW74igaB6puE76LQTdk78/UJEvO87ro0QbjRgJ7TQKpcRU9aID4+kz6JiMkv5FKklu2EeW512CgQXR5YU6f5Ko5pOJko2B+Yq2Zic3J/tRUOcczwUTAg6qIZSvRmTuQclR1k0WiGNydzVxA06LXpnC6zRk9y4ZTRIVpc3MjYajktTuyND0VTDafM1ZuDWxOsnuikGOw1c0tPzMMubTQ9Ed1la8ULXcLjvZCFiAqxzmnemYMdzKPY1w3XerJdVW65MpyT1ixc2Fw8s9x+xVIkIYRGlv1D8qvQ2WPZXiTg+Gf3THOS1IfZrJUeHN+oTHNtehVHKPDMuvJPVHkrP2bg5r6DB7Z0/cMW70++zky75pvfDFZK9/IYP30O1elgfppjnB0J9x+RaZtntlUcgtBnZEeFMPhNiN+ItEwf3MA6gDelKuJjDSRZSnPVHnITL4uxZRBlEZ5xLC+w1PHDaiROzrgm8X24NiColk2IJTlvqMpZ7bOx2k3oXhM/LRwnsBqOE1q9mXWvuxAWzoaTB4H79EnUxqiu67M1hRcn2+x4V8CLBAiAF8IGdDWHXzMdp011XobJZGRgIsMC8R4gBIRBqB8LqyLdtMl6tnYMMEuhvABxbK8xwORbkk7L+nHQYhdZ3hoNSw1G0sJ8w2HCeOC5dXHRf7ZbfbsP0sK+USx9nBrLp8vmYc2nMe44hZTLC1loc67Ijzt+Zjvjb+YjeB7GBGMvGAKyOGOpGSz+0rHeLXsIbEZ5HZVxY/Vp6YrkPFvO7PRnXo00llkrlodja6GTjIFpPztFQd5aegWd2rYHOEO6atkBtl/i71WjZn3AZNkDVzcbpzlqPdEiu8DXaGR5+E9ZcUFVu0+RiMcunFzPc+b2vwDpz2OAqFO0nThmWBc139pmg2md8Qx5XkvaflJo4c68UO0vPdBkvFOUt2PoioSTuPQgm4ikaKA5pNGiRcdaeEJW3WkTJoCQKaDG8dtUK3Om5rfhb4j9TjhwGKxrbaaOAq5xlPWeezZsW0KTdjq0aKdmwdptpc510ahugGZWfaYl0Xcc3HU6KsOKQ2QScd5ccfz7ldCELMZnNRjZB2RM8TkBlvQY0TU1QpO8oXAAN+uPILZRRhKtJqyLSnjQae6neAZU0wnvKGQTu2qktBNaR0MHJ8Iu+PP2FAqOtJwFBnLPfquCETj0R2QQFvBtmWScvIXa1zsiegRP6Y5kDYmHOlsQSJ4BNwUVuZypJeZWTRgCegQXvdlIbvdHLRmfuhufoEzGaS0FqkO7t8gAgE4q3dtGLuAUe0nEgJdzmjEk8Zeiupic1GPH1YR0ZgwbPf7ITrU44dAqGKPhb0n6qpe4685I53wLTqN7P6FiHZ9SoqcQopmfcy08/qbbbPrMcEwyAcnDiCFtsisP8A4/ymIcGCfz/K6OSx4+eLa3TMRjYgxE+qIGg4slwI9F6WDYIZ8r+d4e6ch9nDRruXssptR3+ws8Ym9vweXZ2deq13UfdMt7NeMYd4bPwr0rezWZsLd10+kkWHZbvlcOM2/dI1akXswKu5cnlT2ZDdi17DtE+qas9gMOt6Y4g88DxXroRydDDttHdap2z2VhwbdOwkdFx8RiqkOLobpqUuTz1nZCdInvIbvnbgdpGHqvQdlviNo2NDiDb4D9x0TDLKBQBw3C7/APXHiitsQJ8XiG0C9wcAFxa/xPh6eTV0dShS5+w6YDX1iMbPWnQ49V19gY4SNQMJzmNzqnqqwYLWDGm33mrCK0YV3On0XOnj0lbdHVp0ri8WwluDiRtoRue2SA+C4eZzjKoIo4cqO6cVoOfMTaeBmUq8uOQPH7LnTr5ndDtOIsYrSZl3iwvYcHD3QrZaA0TdQfNlxOSB2pO7ea1rpeZrpYZkE1BSECIS0uhxQ9hoWO8RadJ48FvShmWbgdp01ox6y2xrnYzc0yM8x77dE0+gc3LGWzVq8vDgmG6bQW1wEzIfTPLYvUWMFwDSJiQIdmNy69DDJtNbGtemqdpLYA+z3iy78Jx2SzQLbCF6csQWj3G9eogWLwmYxGOCTtHZ92oBJynkBgul4eNhWGKWax8/t8EMe8mZeRIaNB8IxzXn3Aun4aDAamVATnKq9/2lYxIkiU6n7VXnrRZIday/kJbsppeTUDv4bEZkeRitm2U5AZUmTwx9AhwoN0TEi4YZyOzUrdt1nu+JobsmJ8gTLogshECb3Bs8hIT34cloqug304ydzGbAe7LHHJXbBa3EgnQV6pu1RvldTWVNwos91oAzP5tWkXKRa0Iav3OvhjOmxDMshJAiRycB6lDLnZzG4LaMHyKVMTC+iGi4BcL0kYu9ULideq3imKzxS4GXRhvQnRSc0O6dDyku3Dot4RfYUnVlI6DvKhnu5BCcCqd2Tn0TEYvsKTqWLPAzlxM0FzgMJclYwD+BUdCAzWuWXYVm32Kl+1DkNVcgKsx+BCz5F5PuSQXVARt5BdViuZH3hnZ7NYLv5f5Rm9nwz/w4R3ELChwpfCB/aE9ALsqbpH0CblTn/wBvY8DLEU1waTeymf8AKZyH2KKzsxowht5kfdJsiPHxO5Jllqd8x/OKTqxqL/L2KLF0uw7DgXfh/wCs/cIrWjNnVp+yQ/rTqOf+UN9vOrVycRKrzr6DNPFUVrY1xZ4ZyA4eyM2A0YFeafb3fTwmgO7YcPwrg15z7fRj1L4hS4ieuG9cfs9ZLw8ft12T2jeSUnE7cij/AI0PkVz54erV39zqUcZF7RPcRra5lLj+F1w9ZrJtJY8z7uTtQJHoV5U/qiKMmP8A5Fo+6E79VxThBYdzifVGHw+pHVJfU6dGtfhnp+5iNr3j2jY5wI4YFKRe1XsM+9c6Wt31AmsH/bFpiYNLdlT0RocJ7iCYUyPiN5pn/fJbLDZf329jrUnF8G27tWM9kywEanwcZkkLz1nscVsQvZdIOLZtd+cFrva6I4APc8gASdVoJxlIVlqU3AsDWzJIpkJyMt5UjUjSTSS14OlRmoJqwGHDjvc3w3WyBdMzrpWZXsuz2SDRLKW7ismDFbgM6nMkceKPAtjZkYb6JvD172VrCmIzVFZI9VDeJJe1Pos9tq2zlpmku0O1GsEnEzIMhLOeq6fVTVkc6GHk5aCvasiDOu7ULx/aD2tMiZCRoBN0szL4U32j21MAMdI4H4iMqTxxXkbXawb0y41wPilwJmN6wlTctz0eChk3Y3au0qhrW3Q2Ur1TKWIB/wDKzI9oJNXEnUY7iCaLsaC2QlMEiYEpjmajcmYMEMEojAQcsDvCslGOx0bvZGRFe/G8dNstEG5tPNbEWEyc2CQ2lLmA6dByn7raM3bYWlCLerv6iHdD5jxXRZ54TPArVh2d+cMnjPpNH7s5MA3temKcJS2F6k6NNfqMqHYxmB/1JuHZm5N9UR8OKMG8gQg34wxbE4TK6VHDTe9voc2t8VoU1ovoH/pHnANHJAidnRM7nNqq+OfiLxvp6hVvtPxHr9l0qeDdt0cur8ag/wDFg32NwxcwcfZqVi2M/wDOaP4u9k4YbT8ZHNV7k5RXc1usH3Zz6nxVS4+5kvsX/uz/AIu9kJ1kHzT/ALvZbRgu/wCY4/m0KjoWrzxAP2U8HEweNT/rMQ2baOvso2zHULXMMfO3iJKvdftPFVeGiDxLM4WfaFFo3Ng5hRV8PEHiZdx0fqdw+J5/l7Lv+9jsgTvcViMY3KGSmWQT8oHFYyg+79xWWFw63iarP1PGODR1KM3t6Mc+QWS2Dr90QS0cenqUrVUuLmMsPR4ijYHa8TM8z9gu/wC3pYuJ/a37lZkKzOdhD4lxT8Dsp5+BvIn1XLr/APr3YvKnQjul7Fj+pHmjWOO8+yq7teMcWgb7x6LUs3ZZ+ngJp9lhu0BaDuBK5FStSi9IozjOle0Inn4dsjOx8LdjPdEgwL7vLEdtIujpJelhWBvxlzzvpyWjBZKjIbfXrglZ4yK/avwdKin8vQxrH2DDI8TXz0GHOc+i0oHY7B5WDjX1Wo1jvjIH0tH4Vx8UME7wYNSQD1SE8RVm9zs0WktSsCzBoldby9ArvswdQtddzlQ/4ScTtL5XEgYnAcSVk2v9XMZSr8gGUE9+e9UhQrVHotTp0mrXPRf0zGtk0OH0ivN2aXfbWNAa4ODhTw+y8639RxohrdhsFSAZmupGBMsMVy329wa17Wi+6kNmcvneMJaD/wApmOCmnafPmP0lfc9BaLayHi6TiLxBoQMfFJZHaPbzHNpL7znSnNecNjjxHXXuk2c3V8zzqZTNOS2YP6cDWOc55fWjRhe4YpuFKlQs3K78huCimr7jEH9QPeQ1zqEXZNpI5OEsThzVn9oF7CCC5rJ3nZiU5OA2H7pex2UBrqSuEA7JgmfAp5zmmGHAVeHXmYSF4gnbgTJbOqr/AKUGfTjK2xgNhmIDEaA6RqBsEzRMw4MIgundeZSD6gmcvNpvWnY2tY3vbgbdc5sRjcQBg9o3V5hZ1qiw4hdcDWuAvAOqx7c7un+OV7ym7FpYqKX6dPP8MTfY2n5QayuuB3+H2rsQ4bmsnfuuOAcXih2jHnJAiR4TnSc10JwyLjdmKTa44HfTCqG+0gC7Ea9szR4JkRtu0J4FPUsK5LcQqfE3B2aNKAwPo6KSNJzA+3VXtEKG2VxrC76nNun+0gz4rFZBDSIjHy+rxS/ubhvorxhEZIg1NaOmHT0Iz3EzzC6VDBLucvEfFnfRB7TFig+GFIHRxHIznLeSlv62MBVzg36mB7eYSMS0OPmEznLwOntGB3Bc/rn43p5TdNrt14Y8SU/Tw8Y/wc6rjpz5v8zsa3unUA7WmXRC/qQ74njjP0Kt/UE+aR5AnjKqo9zD8I3VaeidisuzEJVHJ6ohrmDxI9VW7sPqgRJDCY2H3VP6gjGfKfUKyqLkrkb2Gp7Rxopf2cku20zzXe83FaKouGDI+Q18bV3vR8zkv3mxTvG6KZw5AxifUq3tyHNupHBcAGoVXJhyhqbFEK7+TUWLkwWQ82G44lo4IgYweaMdzQFlTn8x5/ZXbAO7p/lJzqtbMDp93b0NVsWzD4XO/c6Q5JmF2rCbhDaPzVY8KBM0bM/nFNsAZVzmtOglP3SFad9G36GM6UXu2/U24PaxPlhHeaDmU4ztJ/yt4C91wC80LYT5RxdT1VX2o5vJ2Nw5lcqrQjJ/yL+EV9El7nrD2g/MtaNrvair/tyEz4r5+kU5ryDYl44E9T1oE1DhEYybsHidxOAS7wkOTWFC27PUf7y6NA6qf7wWiJRkwBi6jQN7sui861hxMgNTWfutCz2UvF5zpQxm6g3NYPzcsnh6UdbIbpwtszSHaEVwud8TrcnIbSfiO081xsRgOLoj9poPfcl2w2u8LZ3Bnh6eiaixWQWyDang47h8I24rJpbRR06EFuxe03n+EzDNJSG66M0vaezoTR4qHQ1edkh5fzFaVl714LjJjZGVJSB+XTf1OCasVhYwh7hXIZndPDep1enp9jq05rnYS7P7H8IiRBdY3yswvHb0mVrWHs4EujRMXGQAoJCga0ZNAQYt+NE8RuwmSnLDYxupKbdamiFEiHBoDWgH4iSIbOhcdgJWFSVSel9X7IY8Qoq+yM8wr0QOlOZIbWTQMJz3+hzK1WPd3Xeyk0OJoMmhrQAOB5TWPDglpgtiTL3kSZQG6BSegqCV6KyuZJ0AmYMN8IHQ3SYruHhbxV3Su4rdfhGc8S8rtv8A7PMWntaGx0V7Re7yG18smzBCp2Za2xId2M66+QIdhMEvdQ6EXhwWT2lFZCjiCZXXsbfOMmtL2gcgSvNujOcYkMkghjC3+E+Uw4rq0MJGWvyZhVxrUbeVj37u0nw4hn423rrgc2ny3Z1ExOU9Mlm9qNEOcSGL7PMAPhM+kxL0OSwrJ2g+JDaHGcRom05uaJzB1IlMcQnYXaDnAvY4Fw8D2ymHA+R0tCaHQkJxYVRadhNYyTTiL/10MtGJbeBBlVrTISkKkg0x0yKlmjAAljw5laTp/aRdIzwkM5LOfDY8uLPDOZunIkSLelDu2pQxnMdM5yJIpOWDho4V6jd1KdNQ2EZ1HPRvU9AIgE+7F2fmbhPeDMDlIzklnxpDw4Zj4STkW/CdxkdTgkW2hrhMGRbpTcQNMiPdDiPM5iU5ZVBG0ZhNJJaoX1ejGXWieGXwnEbjj9tyWjRxiKHhLpil3PvGbaO01/ac/XeuC0A0cOPujnLdOxcxdKbsOWSu20A4jiKHklXtl7oTnI57FlBMfc7QgjQ0KATvCXbEKII/zDijnDkaOuCpeKtIHyn7FUc7VRtcBSLCJtXe8KCSuIZ2WyoP3i616XvFda4IZwOA2HqIQcoq5jPKNNju1A/NisI7RtPPoEkHjQnoEeG06yGynXFIySI4JbjDrQ80ndHLoF2HCGMidpVGxGjAV1VYtrAxNfzJLyizPK3pFDd2eJp0UbEYDIC8ensst9pc7YFGvyH5vWUqdw9F8s2haRmRubRo3nPcF0WmWDZnKdByz4rPs8FxIl+blqwGsZVxrjSv5vS81GOm7KqC2D2azvcZvMzk0ey2e4lLvDXJmct3whYx7Uu0Z4Cc8XncMt5kmLO6Upgue6oZObj9UR2Qzy4YpWdOUtXoMQUY8Gu+0XGgtAc40aB5QfpHxHb6qQrO1hvRDeimt35d+30WRF7UuGTPHFPhL2ijcrkIcZXsdNUIdpiGSA6cT434hn0QtXV82WW2qw0raGyrPg9TaLX3YwvxMm5NJwvbdmO7BVstouziRTOhJO3Jjda85HETn5x1tui8TdAw1AOBOZe7IcaYpez28x3VmITKka6TOfpzQjg9H9zeNW256mN2gYjA1rauJLQJ0mZEjUmeOZI0U7btsOzQ4UMgPeAYl0VBe43S92ycmDUB2qxXdqhhk0gPImX4hjAMW6kDA5k8T5q1doOdEMU4+cA1kGi7CHCm/FMYfBpu7WiKTquR6mxdoviW1gJvPbME4+ORBArgHOl/HYtGNbO5dDmZudNrDr4iC7c4lx/iF5T9GvuOiRzUtYZH6j4Q7/qnvASHafaBLodfKxjf2/G49eqajhVn8krEdV2aW9ytvtRc8vNXXS0Hi8E+vNUiuDjDcMSww3bw0hvqEhDeS6WQJn/Iyn6I9ncSwa3iJ5zkC378k/GK4MGmkWLnBjHiYq4AjKRmDsqSOCZFqIDYzKPBDXjIzwJ3yIPBId94SMjiNK+6HCiTvA4Ood+vNa6EymjbY98l4AEzeMqSJNCNJ4EYTQ2RrxumROLdpzGwnHfvSkKIQC0/mR9+CDfWkXZAcbjT3AGbeX2Xe9+IfmoP5/gb3hzZnzZnU6y/M0uHFp2HrtCOewVC+4w901UxJ0djrrv90EmVRguF01M1y2WwUPLaYjT2VXAGo5IRJVZqrmHKXmuh6oSuTU6lg2CTG5RzjrNDmuzRzpksWvKXlWa4hnZLF7ys1yFNWCCqAaDiS6hAqK2YrYM14HufZcdaBtKUmrBqVci2RchHWhxwpuVAoJKzYio2G1tkGhwZ4lNscxu30SIiE06e6vMDGp0CzlFvcylFvc0W2hzpyN1oxOAG8/ZBfaL1GT2uOJP0j8O5Jvil0rxk0YNFOQ+56osEgeJ1Bk0flEOmohyKJp2OGGeIkXtTUN2n5nbOeakbtMSLWE18xn4n7XuyH0j/ACce1WpztjcgMEFj5Vz9NqKpJu7Cqd9WaMe2ub4WnxESJGQPwt0/ztM72Jt1t92XlBw2uOz15pCyw7zpuwz1OzijW21z8LcMyM5YAaAIuN9EG2tkdj2l0QymTWg1JxO9a0e0iGxtmhmvniuGbsmDY0Y6lYNmiXTezAN392R+6ZgOutLzU0J4+VvHE7AjkTt2QWuBuNGnMEyLpF+xjR4Wz2CR2mWizY0eYO2U9g+Fo2AAKj4pkazLjMnZP7mvAKsIVaDmZnd+TWkUkFRsbIj3LPcBk4g3trSA71urItL5un+YAAdF20Ri6R1meZw6BLokjG2pckgnemWRJBw2h3Ug9H9EmSrh1eEuiKYWrhnmddQeYqgXleGaEaV90JWcuQJcDMyRe0x3f4QXFRryJjVUKGciQQPXL2XLYhqKZw2LNdJQ9FVRVzBLTXFxRWzXIRdmuKKtyHVxRRAh2ak1xRG7IdXQqroKKkAICuKBRWuypRRRRZFji6FFFAh4tBRBb9l1RVWxVbFmZrsTEKKI8k5BvVQooiWGW+VLriiCKoJAx/NCjRvI3bePGcp9FFFbgPIsVdn/AGn0UUUCciY8B6BUUUQIRRRRQhZq47FRRW4AcUUUQCRRRRAhFFFFCEUUUUIRRRREhFFFFCEUUUUIRRRRAhYKKKKwD//Z

**Comment by hov001** [comment]
[Image link](https://user-images.githubusercontent.com/79997615/121490384-ff215380-c9e5-11eb-9ce8-7f539edbd5d9.png)

**Comment by hov001** [comment]
Resolved in #8
